export const LIBRARY = [
  "peaceful morning in the countryside fields bathed in golden sunlight the distant sound of rooster crowing birds chirping in the trees gentle breeze rustling the leaves the smell of dew on the grass flowers blooming in the meadows feeling of serenity and tranquility enveloping everything the vibrant colors of farmer's market stalls overflowing with fresh fruits and vegetables the smell of ripe tomatoes and strawberries filling the air people chatting ",

  "quiet evening at the lake the water still and calm reflecting the colors of the setting sun the sound of crickets chirping in the distance bonfire crackling on the shore marshmallows roasting over the flames friends sharing stories and laughter under the starry sky sense of peace and contentment settling over everything bustling city square alive with activity street performers entertaining the crowd with music and dance the smell of street ",

  "cozy cabin nestled in the woods smoke rising from the chimney the smell of pine trees filling the air crackling fire warming the room blankets piled high on the couch the sound of owls hooting in the distance feeling of peace and solitude enveloping everything and laughing as they browse the produce vendors calling out their specials children running and playing between the stands the energy of community and connection palpable in the atmosphere",

  "sunny afternoon in the garden flowers in full bloom bees buzzing among the blossoms butterflies flitting from flower to flower the sound of water trickling from nearby fountain the smell of freshly cut grass children running and playing games laughter and joy filling the air sense of happiness and contentment food wafting through the air people milling about browsing the various stalls children running and playing games laughter and excitement filling the square sense of joy and camaraderie permeating everything",

  "lively street market filled with vendors selling crafts and artwork the smell of incense hanging in the air colorful tapestries and pottery on display the sound of drums and flutes playing in the background people haggling over prices children running and playing games laughter and chatter filling the streets feeling of excitement and energy in the air fireflies dancing in the twilight the smell of freshly cut grass lingering town ",

  "quiet evening by the fireplace the sound of logs crackling in the flames the warmth of the fire spreading through the room cup of hot cocowarming your hands cozy blanket wrapped around your shoulders the soft glow of candlelight flickering on the walls the sound of wind howling outside feeling of peace and contentment settling over everything filling watch the sun set behind the trees",

  "bustling city market crowded with shoppers vendors calling out their wares the smell of spices and herbs hanging in the air colorful fruits and vegetables piled high on tables people bargaining and haggling over prices children running and playing between the stalls laughter and chatter filling the market sense of excitement and energy palpable in the atmosphere colorful in the air feeling of peace and contentment as you and cotton candy",

  "the excitement of carnival in town colorful lights flashing rides spinning and twirling in the night sky the sound of laughter and screams of joy the smell of popcorn and cotton candy filling the air children running from ride to ride games and prizes lining the midway sense of exhilaration and wonder in the air city market crowded with tranquil evening on the porch rocking chairs creaking softly the sound of crickets chirping in the distance ",

  "busy morning at the farmer's market stalls overflowing with fresh produce the smell of ripe fruit and vegetables filling the air people chatting and laughing as they browse the stands vendors calling out their specials children running people dancing and playing between the stalls the energy of community and connection palpable in the atmosphere",

  "lively night out in the city neon lights flashing music pulsing from clubs and bars people dancing in the streets laughter and chatter filling the air the smell of street food wafting through the streets feeling of excitement and energy as you explore the bustling nightlife the grass flowers blooming in the meadows feeling of serenity and tranquility enveloping everything",

  "peaceful afternoon in the park trees swaying gently in the breeze the sound of birdsong filling the air the smell of freshly cut grass wafting from the lawn children playing on the playground laughter and shouts echoing through the trees families picnicking on the grass blankets spread out under the shade of large oak tree the sun shining brightly in the sky sense of serenity and joy permeating everything",

  "bustling cafe on saturday morning the smell of freshly brewed coffee mingling with the scent of pastries baking in the oven people chatting animatedly with friends and loved ones the clink of cups and plates as they are set down on tables the hum of conversation filling the air baristas calling out orders laughter and smiles all around the warmth of community and connection palpable in the air",

  "quiet evening stroll along the beach the sound of waves crashing against the shore seagulls calling overhead the salty tang of the ocean in the air couples walking hand in hand along the water's edge children playing in the sand building sandcastles the sky painted in shades of pink and orange as the sun sets in the distance feeling of peace and contentment settling over everything",

  "lively street festival in full swing colorful banners fluttering in the breeze the smell of food cooking on grills music filling the air laughter and shouts of joy echoing through the streets children running and playing games vendors selling crafts and trinkets people dancing in the streets the energy of the crowd contagious and exhilarating peaceful morning in the countryside fields bathed in golden sunlight the distant sound of rooster crowing birds chirping in the trees gentle breeze rustling the leaves the smell of dew on ",

  "the busy streets of london crowded market stalls the smell of fresh bread wafting through the air coffee shops bustling with activity people rushing to catch the train laughter and chatter echoing in the streets children playing in the park on sunny day birds chirping in the trees the sound of cars honking in the distance music playing from nearby cafe tables filled with friends enjoying meal the city alive with energy and excitement",

  "beautiful sunset painting the sky in hues of orange and pink gentle breeze blowing through the trees birds singing their evening songs the smell of dinner cooking wafting from nearby homes children playing in the streets laughter and chatter filling the air families gathering around tables to share meal the day winding down as night approaches stars beginning to twinkle in the darkening sky",

  "quiet morning in the countryside fields stretching out to the horizon the soft sound of birds chirping in the trees dew glistening on the grass flowers blooming in the meadows the sun rising slowly in the sky gentle breeze rustling the leaves the smell of fresh coffee brewing in the kitchen peacefulness enveloping everything the world waking up to new day",

  "the hustle and bustle of busy city street people rushing to work cars honking horns taxis weaving through traffic the smell of exhaust fumes hanging in the air sirens blaring in the distance music blasting from open windows the sound of footsteps echoing off tall buildings street vendors selling their wares the energy of the city palpable and alive",

  "cozy evening at home curled up on the couch with good book the soft glow of lamplight filling the room the sound of rain pattering against the windowpane mug of hot tewarming your hands cat purring contentedly in your lap the crackle of fire in the fireplace the smell of cinnamon and cloves drifting from the kitchen feeling of peace and contentment settling over you as you relax and unwind",

  "bustling market square filled with vendors selling their wares the smell of spices hanging in the air colorful fabrics fluttering in the breeze the sound of merchants haggling with customers children running through the crowds laughter and chatter filling the square musicians playing lively tunes on street corners the sun shining down overhead casting everything in warm glow",

  "peaceful afternoon in the park trees swaying gently in the breeze the sound of birdsong filling the air the smell of freshly cut grass wafting from the lawn children playing on the playground laughter and shouts echoing through the trees families picnicking on the grass blankets spread out under the shade of large oak tree the sun shining brightly in the sky sense of serenity and joy permeating everything",

  "bustling cafe on saturday morning the smell of freshly brewed coffee mingling with the scent of pastries baking in the oven people chatting animatedly with friends and loved ones the clink of cups and plates as they are set down on tables the hum of conversation filling the air baristas calling out orders laughter and smiles all around the warmth of community and connection palpable in the air",

  "quiet evening stroll along the beach the sound of waves crashing against the shore seagulls calling overhead the salty tang of the ocean in the air couples walking hand in hand along the water's edge children playing in the sand building sandcastles the sky painted in shades of pink and orange as the sun sets in the distance feeling of peace and contentment settling over everything",

  "lively street festival in full swing colorful banners fluttering in the breeze the smell of food cooking on grills music filling the air laughter and shouts of joy echoing through the streets children running and playing games vendors selling crafts and trinkets people dancing in the streets the energy of the crowd contagious and exhilarating",

  "in the heart of the bustling metropolis skyscrapers towered over the city streets casting long shadows as crowds of people hurried by their footsteps echoing against the concrete pavement nestled among rolling hills quaint village lay tucked away from the hustle and bustle of modern life where time seemed to slow down and the air was filled with the sweet scent of wildflowers",

  "high above the clouds majestic mountain peak pierced the sky its snow capped summit glistening in the sunlight while down below winding trail led adventurous souls on journey of discovery in the depths of the dense jungle ancient ruins lay hidden among towering trees and tangled vines their crumbling walls silent testament to the passage of time and the mysteries of the past",

  "along the rugged coastline jagged cliffs rose from the churning sebattered by crashing waves and buffeted by salty winds while seabirds soared overhead their cries mingling with the roar of the ocean in the heart of the desert towering sand dunes stretched as far as the eye could see their shifting shapes sculpted by the relentless winds while beneath the scorching sun mirages danced on the horizon",

  "amidst fields of golden wheat solitary farmhouse stood against the backdrop of fiery sunset its weathered walls bathed in the warm light of evening as the world seemed to glow with soft amber hue deep beneath the surface of the ocean coral reefs teemed with life their vibrant colors dazzling display against the azure waters while schools of fish darted to and fro in mesmerizing ballet",

  "in the heart of the savannah vast herds of animals roamed across the sun baked plains their hooves stirring up clouds of dust as they journeyed in search of food and water while overhead the blazing sun beat down relentlessly beneath the canopy of vast forest shafts of sunlight filtered through the leaves illuminating the forest floor in golden glow as birds chirped and animals rustled in the underbrush",

  "perched atop rugged cliff medieval castle overlooked the surrounding countryside its imposing towers and battlements testament to bygone erof knights and kings while within its walls echoes of centuries past seemed to linger in the air beneath the canopy of starlit sky crackling campfire cast flickering shadows on the faces of those gathered around it their voices raised in laughter and song as they shared stories and toasted distance the sun dipped marshmallows beneath blanket of twinkling stars",

  "in the depths of the rainforest exotic birds flitted among lush foliage their colorful plumage dazzling sight against backdrop of emerald green while monkeys swung from tree to tree their playful antics filling the forest with laughter peaceful morning in the mountains mist hanging low in the valleys birds singing their morning songs the sound of distant waterfall the smell of pine trees and earthy soil filling the air feeling of serenity and awe as you take in the beauty of nature",

  "on the banks of tranquil river weeping willows dipped their branches into the water their leaves trailing lazily in the current as dragonflies flitted by and the sun danced on the surface in sparkling dance of light in the heart of the vineyard rows of grapevines stretched out as far as the eye could see their ripe fruit hanging heavy on the vine while in the distance the sun dipped below the horizon casting the landscape in warm golden glow",

  "at the foot of towering waterfall crystal clear pool shimmered in the sunlight its waters inviting and cool against the heat of the day as rainbow hued mist rose into the air and the roar of the falls filled the canyon with soothing sound in the midst of bustling market vendors shouted their wares and shoppers bustled about their voices blending into cacophony of sound as the scent of spices and exotic foods filled the air and colorful banners fluttered in the breeze",

  "deep within dense forest hidden glade lay bathed in dappled sunlight its mossy floor soft and inviting beneath the feet as the sweet scent of wildflowers drifted on the breeze and birdsong filled the air with symphony of sound in the heart of the city historic district cobblestone streets wound their way past centuries old buildings their facades adorned with intricate carvings and ornate balconies while the sound of horse drawn carriages echoed through the narrow alleyways toasted marshmallows bustling market",

  "high above the clouds hot air balloon drifted lazily through the sky its brightly colored envelope splash of color against the azure blue as passengers gazed in awe at the breathtaking panoramunfolding beneath them sunny day at the beach waves crashing against the shore seagulls calling overhead children building sandcastles laughter and shouts of joy filling the air the warmth of the sun on your skin feeling of relaxation and contentment as you soak in the beauty of the ocean",
];
